(define (create-function f g)
  (define (calc1 m)
    (if (null? m)
      '()
      (cons (map f (car m))
            (calc2 (cdr m)))))
  (define (calc2 m)
    (if (null? m)
      '()
      (cons (map g (car m))
            (calc1 (cdr m)))))
  (lambda (m)
          (calc1 m)))
